## Zillow CSV Exploration and Cleanup

In [1]:
%matplotlib inline

# Import Dependencies
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## Files being pulled from CSV

* Reading Zillow files
* Creating list to get top 20 cities

In [2]:
DaysonZillowcity_csv = "Zillow_resources/DaysOnZillow_City.csv"
CitymdnlstgPr_Allhomes_csv = "Zillow_resources/City_MedianListingPrice_AllHomes.csv"
Mthlstg_nsa_Allhomes_city_csv = "Zillow_resources/MonthlyListings_NSA_AllHomes_City.csv"

## Reading CSV files using ISO-8859-1

In [3]:
# Read Days on Zillowcity csv
DaysonZillowcity_df = pd.read_csv(DaysonZillowcity_csv, encoding="ISO-8859-1")

# Read City Median listings price on Zillow csv
CitymdnlstgPr_Allhomes_df = pd.read_csv(CitymdnlstgPr_Allhomes_csv, encoding="ISO-8859-1")

# Read Monthly listings nsa Allhomes on Zillow csv
Mthlstg_nsa_Allhomes_city_df = pd.read_csv(Mthlstg_nsa_Allhomes_city_csv, encoding="ISO-8859-1")

# Top 20 cities list
Top20cities = {}

Top20cities = {"CITY":["New York","Los Angeles","Chicago","Houston","Phoenix","Philadelphia","San Antonio","San Diego","Dallas","San Jose","Austin","Jacksonville","San Francisco","Columbus","Fort Worth","Indianapolis","Charlotte","Seattle","Denver","Washington"],
               "STATE":["NY","CA","IL","TX","AZ","PA","TX","CA","TX","CA","TX","FL","CA","OH","TX","IN","NC","WA","CO","DC"]}

Top20cities_df = pd.DataFrame(Top20cities, columns = ["CITY","STATE"])

Top20cities_df

             CITY STATE
0        New York    NY
1     Los Angeles    CA
2         Chicago    IL
3         Houston    TX
4         Phoenix    AZ
5    Philadelphia    PA
6     San Antonio    TX
7       San Diego    CA
8          Dallas    TX
9        San Jose    CA
10         Austin    TX
11   Jacksonville    FL
12  San Francisco    CA
13       Columbus    OH
14     Fort Worth    TX
15   Indianapolis    IN
16      Charlotte    NC
17        Seattle    WA
18         Denver    CO
19     Washington    DC

In [4]:
# Merge dataframes to get 20 cities and states for days on Zillow
DaysonZillowcity_top20_df = pd.merge(DaysonZillowcity_df, Top20cities_df, how='inner',left_on=('RegionName','StateName'),right_on=('CITY','STATE'))

DaysonZillowcity_top20 = DaysonZillowcity_top20_df.loc[:, ["CITY", "STATE", "2017-01", "2017-02", "2017-03", "2017-04", "2017-05", "2017-06", "2017-07", "2017-08", "2017-10", "2017-11", "2017-12","2018-01", "2018-02", "2018-03", "2018-04", "2018-05", "2018-06", "2018-07", "2018-08", "2018-10", "2018-11", "2018-12"]]

DaysonZillowcity_top20.head(20)

,CITY,STATE,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,...,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-10,2018-11,2018-12
0,New York,NY,163.0,163.0,177.0,176.0,173.0,148.0,145.0,144.0,...,166.0,164.0,160.0,123.0,128.0,131.0,137.0,163.0,166.0,167.0
1,Los Angeles,CA,87.0,91.0,68.0,61.0,61.0,60.0,62.0,61.0,...,70.5,55.0,57.0,55.0,56.0,61.0,59.0,66.0,68.0,74.0
2,Chicago,IL,123.0,132.0,119.0,83.0,78.0,81.0,84.5,85.0,...,135.0,98.0,66.0,75.0,84.0,88.0,89.0,99.0,98.0,118.0
3,Houston,TX,97.0,99.0,82.0,72.0,69.0,70.0,70.0,72.0,...,98.0,80.0,66.0,65.0,69.0,73.0,70.0,82.0,91.0,93.0
4,San Antonio,TX,82.0,78.5,69.0,67.0,63.0,60.0,63.0,64.0,...,81.0,63.0,58.0,56.0,56.0,56.0,58.0,66.0,76.0,72.0
5,Philadelphia,PA,99.0,112.0,103.0,90.0,88.0,84.0,87.0,82.0,...,108.0,102.0,80.0,78.0,76.0,75.0,78.0,81.0,80.0,86.0
6,Phoenix,AZ,81.0,76.0,64.0,64.0,63.0,63.0,63.0,62.0,...,70.0,56.0,54.0,54.0,55.0,55.0,56.0,60.0,59.0,63.0
7,San Diego,CA,74.5,66.0,51.0,49.0,48.0,48.0,49.0,49.0,...,49.0,44.0,46.0,46.0,48.0,49.0,48.0,63.0,66.0,72.0
8,Dallas,TX,75.0,78.0,62.0,59.0,57.0,56.0,58.0,58.0,...,82.0,61.0,56.0,56.0,60.0,64.0,68.0,70.0,69.0,76.0
9,San Jose,CA,59.0,41.5,39.0,39.0,39.0,40.0,41.0,39.0,...,35.0,36.0,35.0,35.0,38.0,41.0,43.0,46.0,53.0,60.0
10,Austin,TX,73.0,72.0,50.0,48.0,49.0,49.0,53.0,56.0,...,77.5,51.0,49.0,47.0,50.0,54.0,57.0,65.0,68.0,67.0
11,Jacksonville,FL,103.0,94.5,82.0,76.0,76.0,75.0,73.0,73.0,...,83.0,68.0,61.5,63.0,67.0,68.0,66.0,73.0,72.0,80.0
12,San Francisco,CA,NaN,NaN,40.0,39.0,40.0,42.0,43.0,42.0,...,39.0,38.0,36.0,36.0,39.0,42.0,44.0,37.0,46.0,55.0
13,Indianapolis,IN,94.0,102.0,108.0,81.0,67.0,71.0,69.0,68.0,...,84.0,74.0,60.0,57.0,56.0,57.0,61.0,61.0,64.0,70.0
14,Charlotte,NC,87.5,84.0,59.0,58.0,57.0,58.0,52.0,52.0,...,62.0,48.0,46.0,49.0,51.0,53.0,55.0,61.0,63.0,66.5
15,Fort Worth,TX,61.0,54.0,47.0,48.0,47.0,47.0,48.0,50.0,...,55.0,52.0,47.0,49.0,48.0,48.0,51.0,61.0,60.0,72.0
16,Columbus,OH,78.0,85.0,67.0,57.0,56.0,55.0,54.0,55.0,...,64.0,48.0,51.0,49.0,51.0,51.0,52.0,58.0,59.0,64.0
17,Denver,CO,73.0,59.0,52.0,52.0,48.0,46.0,50.0,50.0,...,46.0,42.0,42.0,42.0,46.0,46.0,49.0,53.0,55.0,63.0
18,Seattle,WA,59.5,39.0,36.0,35.0,35.0,37.0,38.0,38.0,...,34.0,34.0,34.0,35.0,36.0,39.0,42.0,43.0,58.0,72.0
19,Washington,DC,78.0,88.0,57.0,53.0,53.0,54.0,58.0,63.0,...,78.0,60.0,52.0,53.0,57.0,61.0,61.0,59.5,61.0,69.0

In [5]:
# Merge dataframes to get 20 cities and states for median price
CitymdnlstgPr_Allhomes_top20_df = pd.merge(CitymdnlstgPr_Allhomes_df, Top20cities_df, how='inner',left_on=('RegionName','State'),right_on=('CITY','STATE'))

CitymdnlstgPr_Allhomes_top20 = CitymdnlstgPr_Allhomes_top20_df.loc[:, ["CITY", "STATE", "2017-01", "2017-02", "2017-03", "2017-04", "2017-05", "2017-06", "2017-07", "2017-08", "2017-10", "2017-11", "2017-12","2018-01", "2018-02", "2018-03", "2018-04", "2018-05", "2018-06", "2018-07", "2018-08", "2018-10", "2018-11", "2018-12"]]

CitymdnlstgPr_Allhomes_top20

,CITY,STATE,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,...,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-10,2018-11,2018-12
0,New York,NY,699000.0,729000.0,759000.0,792150.5,825000.0,829000.0,813000.0,799000.0,...,799000.0,795000.0,790000.0,815000.0,799000.0,799000.0,779000.0,798000.0,795000.0,798000.0
1,Los Angeles,CA,720000.0,719000.0,729500.0,749000.0,750000.0,750000.0,750000.0,739900.0,...,780000.0,788500.0,799000.0,799000.0,799988.0,799700.0,799000.0,799900.0,799900.0,799000.0
2,Chicago,IL,268750.0,285000.0,299000.0,299900.0,299900.0,305000.0,299999.5,299000.0,...,309000.0,324898.5,329000.0,327250.0,325000.0,324900.0,319900.0,324900.0,319900.0,315000.0
3,Houston,TX,279900.0,280125.0,284900.0,289900.0,294000.0,292000.0,285000.0,284000.0,...,295000.0,299900.0,299999.0,299900.0,299900.0,297500.0,289990.0,293000.0,292990.0,289900.0
4,San Antonio,TX,229682.5,234900.0,239000.0,244481.5,245000.0,245000.0,245000.0,241900.0,...,231499.0,229999.0,235000.0,239900.0,240000.0,239900.0,237000.0,236500.0,239500.0,239992.5
5,Philadelphia,PA,161949.5,165000.0,175000.0,185000.0,189900.0,189900.0,189900.0,185000.0,...,195000.0,199900.0,207000.0,217900.0,224900.0,220000.0,217947.5,214999.0,214900.0,212000.0
6,Phoenix,AZ,255000.0,259900.0,260000.0,269900.0,274900.0,274500.0,274475.0,269995.0,...,279000.0,280000.0,289000.0,289000.0,285000.0,282500.0,279999.0,279900.0,275000.0,275000.0
7,San Diego,CA,609000.0,609900.0,615000.0,635000.0,640000.0,645000.0,645250.0,635000.0,...,638000.0,649000.0,659000.0,709997.0,699950.0,699000.0,689000.0,685000.0,680000.0,679900.0
8,Dallas,TX,355000.0,375000.0,388850.0,399900.0,404900.0,399900.0,394449.5,380000.0,...,395000.0,399000.0,399999.5,400000.0,399000.0,395000.0,379949.5,385000.0,386750.0,375000.0
9,San Jose,CA,769000.0,788000.0,805000.0,819000.0,830000.0,843990.0,839500.0,847500.0,...,975000.0,988000.0,996495.0,998888.0,998000.0,995000.0,980000.0,950000.0,945000.0,939000.0
10,Austin,TX,369539.5,379900.0,389500.0,399900.0,400000.0,399550.0,399000.0,394000.0,...,379900.0,388000.0,389900.0,389900.0,395000.0,395000.0,388945.0,384990.0,380000.0,377990.0
11,Jacksonville,FL,175000.0,178900.0,180000.0,188800.0,194000.0,194900.0,195000.0,194900.0,...,200000.0,205000.0,204500.0,209900.0,210000.0,210000.0,209900.0,210000.0,210000.0,210100.0
12,San Francisco,CA,1150000.0,1195000.0,1195000.0,1195000.0,1195000.0,1190000.0,1167000.0,1160000.0,...,1195000.0,1195000.0,1199000.0,1279500.0,1250000.0,1250000.0,1216500.0,1295000.0,1250000.0,1253461.0
13,Indianapolis,IN,124900.0,125000.0,129900.0,136000.0,144900.0,149900.0,147500.0,147949.5,...,150000.0,155000.0,159900.0,165000.0,165900.0,164900.0,165000.0,166500.0,167000.0,165000.0
14,Charlotte,NC,265000.0,265000.0,272000.0,284900.0,284900.0,285000.0,277990.0,274510.0,...,297277.5,299900.0,299000.0,299000.0,295000.0,289900.0,285000.0,289900.0,289900.0,287990.0
15,Fort Worth,TX,219998.0,226850.0,233000.0,236951.0,238000.0,239900.0,239900.0,238700.0,...,248999.5,249900.0,251990.0,255000.0,256565.0,255000.0,254900.0,255000.0,255000.0,256475.0
16,Columbus,OH,137950.0,139900.0,146900.0,154900.0,160000.0,164837.5,164900.0,164900.0,...,160000.0,160000.0,169000.0,174900.0,179900.0,179900.0,175000.0,171000.0,169900.0,166332.5
17,Denver,CO,455000.0,465000.0,475000.0,489900.0,479900.0,479000.0,475000.0,480000.0,...,475000.0,485000.0,489000.0,485000.0,479900.0,474974.5,465000.0,469000.0,465000.0,459900.0
18,Seattle,WA,599000.0,599950.0,616000.0,625000.0,645000.0,650000.0,657000.0,649950.0,...,699000.0,725000.0,719950.0,735000.0,725000.0,725000.0,700000.0,699950.0,699000.0,689900.0
19,Washington,DC,549000.0,549000.0,549000.0,550000.0,569000.0,569000.0,550000.0,529900.0,...,549900.0,565000.0,585000.0,595000.0,599000.0,585000.0,575500.0,589900.0,584900.0,574999.0

In [6]:
# Merge dataframes to get 20 cities and states for monthly listings
Mthlstg_nsa_Allhomes_city_top20_df = pd.merge(Mthlstg_nsa_Allhomes_city_df, Top20cities_df, how='inner',left_on=('RegionName','StateName'),right_on=('CITY','STATE'))

Mthlstg_nsa_Allhomes_city_top20 = Mthlstg_nsa_Allhomes_city_top20_df.loc[:, ["CITY", "STATE", "2017-01", "2017-02", "2017-03", "2017-04", "2017-05", "2017-06", "2017-07", "2017-08", "2017-10", "2017-11", "2017-12","2018-01", "2018-02", "2018-03", "2018-04", "2018-05", "2018-06", "2018-07", "2018-08", "2018-10", "2018-11", "2018-12"]]

Mthlstg_nsa_Allhomes_city_top20

,CITY,STATE,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,...,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-10,2018-11,2018-12
0,New York,NY,21414.0,22063.0,20735.0,19054.0,19878.0,18795.0,18326.0,18009.0,...,20867.0,18650.0,20131.0,21956.0,21285.0,20792.0,20748.0,22969.0,21115.0,19013.0
1,Los Angeles,CA,5499.0,5656.0,6502.0,5958.0,6754.0,6470.0,6160.0,6755.0,...,5060.0,5286.0,5663.0,6564.0,6474.0,6787.0,7445.0,7975.0,7173.0,6180.0
2,Chicago,IL,9293.0,9641.0,10892.0,10289.0,11429.0,11041.0,11049.0,11812.0,...,9236.0,10529.0,10812.0,11637.0,11142.0,11357.0,12071.0,12101.0,10325.0,8929.0
3,Houston,TX,10247.0,10648.0,12006.0,11607.0,12919.0,12546.0,13095.0,13511.0,...,10241.0,11235.0,11859.0,13068.0,12522.0,12880.0,13775.0,13230.0,11994.0,11294.0
4,San Antonio,TX,4794.0,5065.0,5626.0,4944.0,5536.0,5485.0,5844.0,6146.0,...,5266.0,5538.0,5622.0,6472.0,6316.0,6513.0,7320.0,6818.0,6382.0,6043.0
5,Philadelphia,PA,5755.0,5968.0,6298.0,5838.0,6242.0,5850.0,5956.0,6343.0,...,5162.0,5339.0,5649.0,6139.0,5679.0,5595.0,6048.0,6494.0,5917.0,5296.0
6,Phoenix,AZ,6965.0,7531.0,8111.0,7489.0,7874.0,7072.0,6974.0,7280.0,...,6714.0,6709.0,6938.0,7416.0,6862.0,6588.0,6954.0,7082.0,6543.0,6164.0
7,San Diego,CA,2297.0,2520.0,2733.0,2590.0,2983.0,2661.0,2774.0,3118.0,...,2451.0,2595.0,2903.0,3394.0,3301.0,3638.0,4085.0,4058.0,3612.0,3163.0
8,Dallas,TX,2998.0,3088.0,3430.0,3216.0,3545.0,3366.0,3605.0,4310.0,...,3535.0,3808.0,4097.0,4553.0,4392.0,4484.0,4752.0,4918.0,4561.0,4042.0
9,San Jose,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Austin,TX,2637.0,2735.0,3115.0,3227.0,3834.0,3554.0,3671.0,3865.0,...,2670.0,2879.0,3244.0,3794.0,3664.0,3742.0,3909.0,3658.0,3127.0,2672.0
11,Jacksonville,FL,4282.0,4673.0,4948.0,4591.0,5026.0,4668.0,4688.0,5187.0,...,4336.0,4538.0,4635.0,5114.0,4943.0,5141.0,5456.0,5592.0,5155.0,4736.0
12,Charlotte,NC,2208.0,2455.0,2609.0,2604.0,2858.0,2731.0,2844.0,3094.0,...,2466.0,2753.0,2914.0,3373.0,3215.0,3285.0,3554.0,3564.0,3108.0,2686.0
13,Fort Worth,TX,2133.0,2086.0,2262.0,2088.0,2569.0,2568.0,2884.0,3652.0,...,2579.0,2826.0,3061.0,3619.0,3646.0,3817.0,4145.0,3969.0,3476.0,3079.0
14,Columbus,OH,1706.0,1738.0,1690.0,1462.0,1777.0,1753.0,1893.0,2228.0,...,1089.0,1239.0,1343.0,1702.0,1675.0,1848.0,2272.0,2316.0,1958.0,1684.0
15,Denver,CO,1632.0,1800.0,2026.0,1809.0,2667.0,2628.0,2619.0,2853.0,...,1638.0,1818.0,2007.0,2444.0,2397.0,2480.0,2857.0,3069.0,2558.0,2168.0
16,Seattle,WA,864.0,957.0,1180.0,1168.0,1559.0,1440.0,1441.0,1450.0,...,826.0,1042.0,1230.0,1626.0,1796.0,1799.0,2046.0,2559.0,2093.0,1612.0
17,Washington,DC,1470.0,1572.0,1773.0,1646.0,1982.0,1949.0,1819.0,1736.0,...,1868.0,2009.0,2271.0,2510.0,2134.0,2069.0,2024.0,2507.0,2208.0,1834.0

In [7]:
Mthlstg_nsa_Allhomes_city_top20.to_csv("Zillow_resources/Output/MonthlyListings_NSA_AllHomes_City_final.csv",
                  encoding="utf-8", index=False, header=True)

In [8]:
CitymdnlstgPr_Allhomes_top20.to_csv("Zillow_resources/Output/City_MedianListingPrice_AllHomes_final.csv",
                  encoding="utf-8", index=False, header=True)

In [9]:
DaysonZillowcity_top20.to_csv("Zillow_resources/Output/DaysOnZillow_City_final.csv",
                  encoding="utf-8", index=False, header=True)